def generate_html_report(results, file_path):

    html = """
<html>

<head>
<title>Code Analysis Report</title>

<style>

body{
    font-family: 'Segoe UI', Arial, sans-serif;
    background:#f4f6f8;
    margin:0;
}

.wrapper{
    max-width:1100px;
    margin-left:auto;
    margin-right:auto;
    padding:40px;
}

.header{
    background:#2ecc71;
    color:white;
    padding:25px;
    border-radius:10px;
    box-shadow:0 4px 10px rgba(0,0,0,0.15);
}

.header h1{
    margin:0;
}

.file-box{
    background:white;
    margin-top:20px;
    padding:15px;
    border-radius:8px;
    box-shadow:0 2px 6px rgba(0,0,0,0.1);
}

.results{
    margin-top:30px;
}

.card{
    background:white;
    padding:18px;
    border-radius:8px;
    margin-bottom:15px;
    box-shadow:0 2px 6px rgba(0,0,0,0.1);
    display:flex;
    justify-content:space-between;
    font-size:16px;
}

.label{
    font-weight:600;
}

.value{
    color:#333;
}

.footer{
    margin-top:40px;
    text-align:center;
    color:#777;
    font-size:13px;
}

</style>

</head>


<body>

<div class="wrapper">

<div class="header">
<h1>Automated Code Complexity Analyzer</h1>
<p>Static Code Analysis Report</p>
</div>

<div class="file-box">
<b>Analyzed File:</b> """ + file_path + """
</div>

<div class="results">

<div class="card">
<span class="label">Maximum Loop Depth</span>
<span class="value">""" + str(results["max_loop_depth"]) + """</span>
</div>

<div class="card">
<span class="label">Estimated Time Complexity</span>
<span class="value">""" + str(results["time_complexity"]) + """</span>
</div>

<div class="card">
<span class="label">Total Loops Found</span>
<span class="value">""" + str(results["total_loops"]) + """</span>
</div>

<div class="card">
<span class="label">Cyclomatic Complexity</span>
<span class="value">""" + str(results["cyclomatic_complexity"]) + """</span>
</div>

<div class="card">
<span class="label">Recursion Detected</span>
<span class="value">""" + str(results["recursion"]) + """</span>
</div>

<div class="card">
<span class="label">Infinite Loop Risk</span>
<span class="value">""" + str(results["infinite_loop"]) + """</span>
</div>

<div class="card">
<span class="label">Unused Variables</span>
<span class="value">""" + str(results["unused_variables"]) + """</span>
</div>

<div class="card">
<span class="label">AI Bug Detection</span>
<span class="value">""" + str(results["ai_bugs"]) + """</span>
</div>

</div>

<div class="footer">
Generated by Code Complexity Analyzer
</div>

</div>

</body>
</html>
"""

    with open("report.html", "w") as f:
        f.write(html)

    print("HTML report generated successfully: report.html")
